#!/bin/bash
#PBS -l select=1:ncpus=48:mpiprocs=8
#PBS -l walltime=999:00:00
#PBS -j oe
#PBS -M maykcaldas@gmail.com
#PBS -m bea
#PBS -V
#PBS -N QuercetinG0

# load modules
module load openmpi-gnu/2.1.1
source /scratch/60061a/plumed2/sourceme.sh
# change directory
cd $\{PBS_O_WORKDIR\}
# environment (if necessary)
export PLUMED_NUM_THREADS=1
export OMP_NUM_THREADS=6

# run
runmd.sh
