#!/bin/bash
#PBS -l select=4:ncpus=48:mpiprocs=8
#PBS -l walltime=999:00:00
#PBS -j oe
#PBS -V
#PBS -N QCT2A

# load modules
module load openmpi-gnu/2.1.1
source /scratch/60061a/plumed2/sourceme.sh
# change directory
cd ${PBS_O_WORKDIR}
# environment (if necessary)
export PLUMED_NUM_THREADS=1
export OMP_NUM_THREADS=6
# run


/scratch/60061a/maykcaldas/Dendrimer/Quercetin/G2/Acid/run.sh
